/*
 * MapInstanceMessage.h
 *
 *  Created on: 2014年6月3日
 *      Author: root
 *      地图副本消息
 */

#ifndef MAPINSTANCEMESSAGE_H_
#define MAPINSTANCEMESSAGE_H_

#include "Network/MessageHandler.h"
#include "MsgDefineMacro.h"
#include "ServerMsgDefine.h"
#include <map>
#include <vector>
#include "../Object/Player/Player.h"
#include "../QuickMessage.h"
#include "MessageStruct/CharLogin/MapInstanceProto.pb.h"

using namespace std;
using namespace CommBaseOut;

class MapInstanceMessage : public Singleton<MapInstanceMessage>, public Ack_Handler, public Request_Handler, public Message_Handler
{
public:
	MapInstanceMessage();
public:
	~MapInstanceMessage();
	//void Init();

	//////////////////////////////////////////////new instance///////////////////////////////////////////////////////////////

	virtual void Handle_Ack(Safe_Smart_Ptr<Message> &message);
	virtual void Handle_Request(Safe_Smart_Ptr<Message> &message);
	virtual void Handle_Message(Safe_Smart_Ptr<Message> &message);


	DEF_MSG_REQUEST_DECLARE_FUN_H(MSG_REQ_WS2GM_CLAN_WARGATER);

	DEF_MSG_SIMPLE_DECLARE_FUN_H(MSG_SIM_WS2GM_LEAVE_CLANWAR);
	DEF_MSG_SIMPLE_DECLARE_FUN_H(MSG_SIM_WS2GM_CLANCITYREWARD);
	DEF_MSG_SIMPLE_DECLARE_FUN_H(MSG_SIM_WS2GM_MATCH_PLAYER);
	DEF_MSG_SIMPLE_DECLARE_FUN_H(MSG_SIM_WS2GM_ALREADY_MATCH_PLAYER);
	DEF_MSG_SIMPLE_DECLARE_FUN_H(MSG_SIM_WS2GM_CANCEL_MATCH_PLAYER);

	DEF_MSG_ACK_DECLARE_FUN_H(MSG_REQ_GM2WS_CREATEINSTANCE);
//	DEF_MSG_ACK_DECLARE_FUN_H(MSG_REQ_GM2DB_ARENAINFO);
//	DEF_MSG_ACK_DECLARE_FUN_H(MSG_REQ_GM2WS_SYNCARENA);

	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_CREATEINSTANCE);	//创建副本
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_MAP_ALL_CREATURE);
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_BEYOND_SERVER_INFO);
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_GET_BEYOND_REWARD);

	//////////////////////////////////////////////new instance///////////////////////////////////////////////////////////////


	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GT_LEAVEINSTANCE);		//副本

	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GT_SWEEPINSTANCE);		//扫荡副本
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GT_SWEEPSPEEDUP);		//扫荡加速
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GT_RESETINSTANCE);		//重置副本
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GT_RESETALLINSTANCE);		//重置所有副本
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GT_OPENINSTANCESWEEP);
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GT_GETREWARDS);			//领取奖励
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GT_ENTERINSTANCE);			//进入副本检查
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GT_INSTANCETEAMINFO);	//获取副本队伍信息

	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GT_INSTANCEGROUPREADY);	//组队副本准备信息
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GT_INSTANCEGROUPENTER);	//组队副本进入信息
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GT_MEMBERFLOPINFO);			//组队副本翻牌信息
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_UPDATEINSTANCEMONSTERPOS);	//

	DEF_MSG_QUICK_SIMPLE_DECLARE_FUN_H(MSG_REQ_C2GT_UPDATEINSTANCE);		   //更新副本信息
	DEF_MSG_QUICK_SIMPLE_DECLARE_FUN_H(MSG_REQ_C2GT_SWEEPINSTANCEEND);	//扫荡副本结束



	DEF_MSG_REQUEST_DECLARE_FUN_H(MSG_REQ_WS2GM_GROUP_LIMIT);

	DEF_MSG_REQUEST_DECLARE_FUN_H(MSG_REQ_WS2GM_INVITLIMIT);

	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_LOTTERY);//VIP副本抽奖

	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_MATCH_PLAYER);//匹配对手

	DEF_MSG_ACK_DECLARE_FUN_H(MSG_REQ_GM2WS_MATCH_PLAYER); //匹配对手

	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_SWEEPALLINSTANCE);//请求一键扫荡
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_STOPSWEEPALLINSTANCE);//取消一键扫荡

	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_ASKINSTANCERANK); //请求副本排名
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_FINISH_GUIDE);	//完成指引


	DEF_MSG_REQUEST_DECLARE_FUN_H(MSG_REQ_WS2GM_MARRY_CARBON_LIMIT);

	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_SUPPORT_ANOTHER);

	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GS_HEROINFO);//请求英雄副本信息
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GS_FITCH_HERO_BOX);//请求领取宝箱额外奖励

	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_GROUPINSTANCE_INFO);//请求组队副本信息
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_SHOPPING_GROUPINSTANCE);//请求购买组队副本
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_ELITE_INFO); //获取精英副本信息
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_CAUCHEMAR_INFO); //获取恶梦副本信息
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_ADVANCED_INFO); //获取进进阶副本信息
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_INSTANCE_INFO); //获取普通副本信息
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_EXP_INFO); //获取经验副本信息
	DEF_MSG_QUICK_REQUEST_DECLARE_FUN_H(MSG_REQ_C2GM_MONEY_INFO); //获取铜钱副本信息
};



#endif /* MapInstanceMessage */
