protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/CharLogin/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/SysGT2LS/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/Map/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/CharBase/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/Quest/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/CharBattle/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/Friend/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/Group/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/Meridians/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/Mall/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/RewardHail/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/Daily/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/WorldBoss/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/Escort/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/Answer/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/MonitorMap/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/Clan/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/MSProtoc/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/AntiAddiction/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/Activity/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/GirlWar/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/BeyondServerBattle/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/SystemNotice/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/Market/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/Marry/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/Country/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/RedEnvelope/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/FestivalActive/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/Pay/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/InterfaceAnswer/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/PVP/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/MoneyInsatence/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/CDTime/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/Seabeach/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/ChristmasActivity/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/Fashion/*.proto
protoc -I=./Protolbuf --cpp_out=./MessageStruct ./Protolbuf/BaseShop/*.proto


