################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
C++_DEPS := 
OBJS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/Worship \
src/WorldBoss \
src/Vitality \
src/Vitality/VitalityLoader \
src/VIP \
src/Trade \
src/SysSetting \
src/StatisticMgr \
src/Skill \
src/Skill/SkillLoader \
src/Skill/Effect \
src/Settings \
src \
src/Seabeach \
src/RewardHail \
src/RewardHail/FileLoader \
src/Recharge \
src/QuestNew \
src/PVP \
src/Order \
src/Object/PlayerRegion \
src/Object/Player \
src/Object \
src/Object/NPC \
src/Object/Monster \
src/Object/ItemDrop \
src/Object/GirlWar \
src/Object/GirlWar/AI \
src/Object/FileLoader \
src/Object/AI \
src/MonsterExpParam \
src/MoneyShop \
src/Meridians \
src/Meridians/FileLoader \
src/Meditation \
src/Marry \
src/Marry/MarryLoader \
src/MapInstance \
src/MapInstance/CrossSvrCompetitionLoader \
src/MapCarbon \
src/Map \
src/Map/ReflushManage \
src/Map/ConfigLoader \
src/ManagerServerMgr \
src/Mall \
src/Mail \
src/MagicWeapon \
src/MagicWeapon/MagicLoader \
src/Magic \
src/MSOpreation \
src/LucklyTurntable \
src/Horse \
src/Horse/HorseLoader \
src/HeartMagic \
src/GuideFileLoader \
src/Group \
src/GMInterfaceAnswerMessage \
src/Fighting \
src/FestivalUI \
src/Festival \
src/Fashion \
src/Fashion/FashionLoader \
src/ExtraAtribute \
src/EscortEx/FileLoader \
src/EscortEx \
src/Escort \
src/EquipSmith/MaterialSynthesis \
src/EquipSmith/EquipSmithEx \
src/EquipSmith/EquipSmith \
src/Distortion \
src/Destination \
src/DanLu \
src/Daily \
src/CountryRedEnvelope \
src/Country \
src/Counter \
src/Container \
src/Container/ContailerLoader \
src/ConfigLoader \
src/Clan \
src/Clan/ClanLoader \
src/Chat \
src/CJobLucky \
src/CJobLucky/CJobLuckyLoader \
src/CDTime \
src/Attribute \
src/Arena \
src/AntiAddictionSystem/FileLoader \
src/AntiAddictionSystem \
src/Activity \
src/Activity/FileLoader \
src/ActiveUIHighLight/HintLoader \
src/ActiveUIHighLight \
src/Achievement \

