// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CharLogin/DayUpdate.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CharLogin/DayUpdate.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace DayUpdate {

namespace {

const ::google::protobuf::Descriptor* DayInfoUpdate_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DayInfoUpdate_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CharLogin_2fDayUpdate_2eproto() {
  protobuf_AddDesc_CharLogin_2fDayUpdate_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CharLogin/DayUpdate.proto");
  GOOGLE_CHECK(file != NULL);
  DayInfoUpdate_descriptor_ = file->message_type(0);
  static const int DayInfoUpdate_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DayInfoUpdate, info_),
  };
  DayInfoUpdate_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DayInfoUpdate_descriptor_,
      DayInfoUpdate::default_instance_,
      DayInfoUpdate_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DayInfoUpdate, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DayInfoUpdate, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DayInfoUpdate));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CharLogin_2fDayUpdate_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DayInfoUpdate_descriptor_, &DayInfoUpdate::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CharLogin_2fDayUpdate_2eproto() {
  delete DayInfoUpdate::default_instance_;
  delete DayInfoUpdate_reflection_;
}

void protobuf_AddDesc_CharLogin_2fDayUpdate_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\031CharLogin/DayUpdate.proto\022\tDayUpdate\"\035"
    "\n\rDayInfoUpdate\022\014\n\004info\030\001 \003(\005", 69);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CharLogin/DayUpdate.proto", &protobuf_RegisterTypes);
  DayInfoUpdate::default_instance_ = new DayInfoUpdate();
  DayInfoUpdate::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CharLogin_2fDayUpdate_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CharLogin_2fDayUpdate_2eproto {
  StaticDescriptorInitializer_CharLogin_2fDayUpdate_2eproto() {
    protobuf_AddDesc_CharLogin_2fDayUpdate_2eproto();
  }
} static_descriptor_initializer_CharLogin_2fDayUpdate_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int DayInfoUpdate::kInfoFieldNumber;
#endif  // !_MSC_VER

DayInfoUpdate::DayInfoUpdate()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void DayInfoUpdate::InitAsDefaultInstance() {
}

DayInfoUpdate::DayInfoUpdate(const DayInfoUpdate& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void DayInfoUpdate::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DayInfoUpdate::~DayInfoUpdate() {
  SharedDtor();
}

void DayInfoUpdate::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DayInfoUpdate::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DayInfoUpdate::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DayInfoUpdate_descriptor_;
}

const DayInfoUpdate& DayInfoUpdate::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CharLogin_2fDayUpdate_2eproto();
  return *default_instance_;
}

DayInfoUpdate* DayInfoUpdate::default_instance_ = NULL;

DayInfoUpdate* DayInfoUpdate::New() const {
  return new DayInfoUpdate;
}

void DayInfoUpdate::Clear() {
  info_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DayInfoUpdate::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 info = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_info:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 8, input, this->mutable_info())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_info())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(8)) goto parse_info;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void DayInfoUpdate::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated int32 info = 1;
  for (int i = 0; i < this->info_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      1, this->info(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* DayInfoUpdate::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated int32 info = 1;
  for (int i = 0; i < this->info_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(1, this->info(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int DayInfoUpdate::ByteSize() const {
  int total_size = 0;

  // repeated int32 info = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->info_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->info(i));
    }
    total_size += 1 * this->info_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DayInfoUpdate::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DayInfoUpdate* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DayInfoUpdate*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DayInfoUpdate::MergeFrom(const DayInfoUpdate& from) {
  GOOGLE_CHECK_NE(&from, this);
  info_.MergeFrom(from.info_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DayInfoUpdate::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DayInfoUpdate::CopyFrom(const DayInfoUpdate& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DayInfoUpdate::IsInitialized() const {

  return true;
}

void DayInfoUpdate::Swap(DayInfoUpdate* other) {
  if (other != this) {
    info_.Swap(&other->info_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DayInfoUpdate::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DayInfoUpdate_descriptor_;
  metadata.reflection = DayInfoUpdate_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace DayUpdate

// @@protoc_insertion_point(global_scope)
